# Generated by Django 5.1.2 on 2024-10-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onlineShop',
            field=models.BooleanField(default=False),
        ),
    ]
