# Generated by Django 5.1.2 on 2024-10-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_onlineshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
