# Generated by Django 5.1.2 on 2024-10-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=200)),
                ('pinCode', models.CharField(max_length=50)),
                ('business_creation_date', models.DateTimeField(auto_now_add=True)),
                ('logo', models.CharField()),
                ('business_address', models.TextField()),
                ('business_phone', models.CharField(max_length=15)),
                ('business_website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='login.user')),
            ],
        ),
    ]
