# Generated by Django 5.1.2 on 2024-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_businessprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='pinCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
